### PR TITLE
Progress bar

### PR DESCRIPTION
**Pull request by KennyImarah**
Progress Bar. Sorry for delays.

### CODE REVIEW

**Comment by JaredHook** [comment]
there are no files to be commited and this pull request is to master2, which should be for develop

**Review by jp-2019 — CHANGES_REQUESTED** [review]
pull request should not be to master2

**Comment by shakirullah7892** [comment]
I agree with Jared and Jeannie. If you would like assistance we are here to help.

**Comment by KennyImarah** [comment]
Progress bar closed

**Pull request closed without merging**
